### ISSUE TITLE
how to add and modify pages?

### ISSUE THREAD

**Issue by aoyawale** [aubm/hugo-code-editor-theme#2]
hello,

how do I add or modify pages for this theme? sorry new to hugo and I'm trying to understand.

**Comment by aubm** [comment]
Hello! I think your question is not specific to the theme.
Did you read the Hugo quick start already? https://gohugo.io/overview/quickstart/

**Comment by aoyawale** [comment]
thanks for the help. I was able to create content now and display it. Now the part i'm stuck is how to be able to create categories on the left side and list the pages there. I'm looking at the hugo docs but, can't find that part.

**Comment by aubm** [comment]
If you look at the [demo web site](http://themes.gohugo.io/theme/hugo-code-editor-theme/), you have an idea of what you can get from the theme: the category list displayed below the tag list.

Here si some doc about attaching some content to one or multiple categories: https://gohugo.io/taxonomies/usage/.
