### ISSUE TITLE
Feature request: Make Root link destination in menu.html configurable

### ISSUE THREAD

**Issue by tivec** [aubm/hugo-code-editor-theme#5]
I've recently started using this theme and I quite like the way it looks. However, at the top of menu.html you are defining a root link to be `<a href="/">`. 

I suggest that you instead of the / put in the baseurl from the config.toml file, or add a parameter to configure it.

**Comment by aubm** [comment]
Hey, ok good idea.
If you want to submit a PR, I will be pleased to merge it :)
